### ISSUE TITLE
Visualize annotations using point pairs and transformation parameters to determine which is cleaner 

### ISSUE THREAD

**Issue by fmpaezri** [jccaicedo/localization-agent#29]
If transform parameters seem cleaner make an experiment using those values in the cost

**Comment by jccaicedo** [comment]
Also, have a look at the bounding box regression setting in the following papers:
http://arxiv.org/abs/1504.08083
http://arxiv.org/abs/1506.01497

They use x,y offsets and log-scale offsets too (4 values to predict). The cost function could also be implemented instead of just squared error as we currently have.

**Comment by fmpaezri** [comment]
Added ground truth graphs to [this notebook](https://github.com/jccaicedo/localization-agent/blob/pairedFrameTracker/notebooks/Test%20data%20trajectory%20analysis.ipynb). My supposition was wrong, transform parameters do not seem to be much cleaner than x,y pairs GT. First of all because the first x,y of the GT match the x,y of the transform params. What I saw was that "sometimes" when the scale does not change too much, the last x,y may be correlated to the first x,y. But  scales may be correlated between them "sometimes" if the object tends to keep its aspect ratio. The only way to know which parametrization is better is to perform experiments. Review the practices in the Fast-RCNN papers and apply what we consider relevant.
